apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.deploymentName }}
  namespace: {{ .Values.app.namespace }} 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ include "go.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "go.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
