apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.serviceName }}
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    {{ include "go.labels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
